### ISSUE TITLE
Compiled Package Version Release

### ISSUE THREAD

**Issue by hieonn** [FelixKratz/JupyterApp-mac#1]
It is incredible! 

Do you have any plan to provide compiled package version release? I don't want to use Xcode to use the fantastic artifacts. It would be great work if you do. Thanks.

**Comment by FelixKratz** [comment]
Glad you like it. I only have the free Apple Developer Account, so I don't know if the apps that I sign will run on your device.
You can try it though using the executable from the latest release: [https://github.com/FelixKratz/JupyterApp-mac/releases/tag/v0.3](https://github.com/FelixKratz/JupyterApp-mac/releases/tag/v0.3).

Please let me know if the compiled app runs on your system.

**Comment by ym-han** [comment]
> Glad you like it. I only have the free Apple Developer Account, so I don't know if the apps that I sign will run on your device.
> You can try it though using the executable from the latest release: https://github.com/FelixKratz/JupyterApp-mac/releases/tag/v0.3.
> 
> Please let me know if the compiled app runs on your system.

I haven't really put this through its paces, but I can at least open notebooks and run simple commands with the compiled app. I did have to go to my system preferences because it was automatically blocked from opening, but that wasn't much of an obstacle.

Looking forward to playing with this. Thanks for developing this!
